### ISSUE TITLE
HALS and FFT method broken

### ISSUE THREAD

**Issue by ds138** [HydroGeoSines/HydroGeoSines#35]
Both methods do not function correctly when BP records are present. There might be an issue with the **categories** variable defined for all data outside of the groupby loop. But it might also be due to the filtering method of the ** if cat != "GW":**. This results in the following problems:

-  The method reports the data category BP but it break, because of the harmonic_lsqr() method criteria of <= 20 days. Which is 0 if non of the BP and GW data align. Does the BP data have to be aligned with the GW data at this step, even if it is irregularly sampled? If so, the BP data needs to be resampled at this step.

**Comment by ds138** [comment]
I have implemented a possible solution in a commit on my branch. It allows the BP data for HALS to be non-aligned with the GW data and it does not have to be regularly sampled. It only takes all BP records within the same sampling period as the GW data using the following code:

```python
if (GW.datetime.isin(group.datetime)).all():                             
    filter_gw = group.datetime.isin(GW.datetime)
    group = group.loc[filter_gw,:]
else:
    # for irregularly sampled data that is also not aligned
    dt_start = GW["datetime"].min()
    dt_end = GW["datetime"].max()
    mask = (group["datetime"] >= dt_start) & (group["datetime"] <= dt_end)
    group = group.loc[mask]
```

I created a short notebook in our examples called "HALS" for this so you can have a look!

**Comment by hydrogeoscience** [comment]
I have reviewed and merged this into the master branch
