### ISSUE TITLE
Update_commdat.py issue with imports

### ISSUE THREAD

**Issue by callumj2** [HydroGeoSines/HydroGeoSines#40]
Running Update_commdat.py raises an error on my machine (Python 3.8.5) when calling urllib.request.

This issue was fixed by replacing line 15 with

```  import urllib.request ```

**Comment by hydrogeoscience** [comment]
Thanks for reporting. This issue should now be resolved as part of separating PyGTide from this package, see: https://github.com/HydroGeoSines/HydroGeoSines/issues/43#issuecomment-1158589689
