### ISSUE TITLE
Issue importing barometric CSV to existing site

### ISSUE THREAD

**Issue by callumj2** [HydroGeoSines/HydroGeoSines#42]
Hi guys,

When running through all of the example notebooks, I came across the following error in the dataset_preprocessing and example_2 notebooks:

![image](https://user-images.githubusercontent.com/66106348/174225972-398cef68-b612-468b-9286-f9390f8e96ff.png)

There appears to be an issue with the import_csv function for barometric data, as the previous call to example_site.data gives the following:

![image](https://user-images.githubusercontent.com/66106348/174226071-7e7f12b8-5262-4de1-8415-76a8c83d6861.png)

It looks like it has put the unit as ‘BP’ and the category as ‘m’, switching the two somewhere along the way. 

I found that merging the datasets into one csv gets rid of the error, but I haven’t yet checked if it is all working correctly. To merge I used a simple outer join which results in a lot of NaN's present in the imported dataset (See merge code below).

![image](https://user-images.githubusercontent.com/66106348/174226257-d9b21b26-7fc1-4934-b426-8fd8ac55ded8.png)

**Comment by hydrogeoscience** [comment]
Thanks for reporting. This should now be fixed.
