### ISSUE TITLE
Etpred import requires Python 3.8

### ISSUE THREAD

**Issue by callumj2** [HydroGeoSines/HydroGeoSines#43]
Hi guys,

I found that getting HGS up and running required me to create a virtual environment of the previous Python version 3.8 in order to import the etpred library. 

I think this could be something to include in the documentation and README.

Cheers!

**Comment by hydrogeoscience** [comment]
Yes, this problem is because PyGTide contains an executable made for certain platforms and python versions. 

I have just separated this package from PyGTide. This means that PyGTide must be separately installed. This should solve the problem that you observed.
